apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: backend-destination-rule
spec:
  host: backend
  trafficPolicy:
      connectionPool:
        http: {}
        tcp: {}
      loadBalancer:
        simple: ROUND_ROBIN
      outlierDetection:          #Detect error with condition
        consecutiveErrors: 1     #If found 1 consecutive error (consecutiveErrors)
        baseEjectionTime: 15m     #then eject that pod from pool for 15 minutes (baseEjectionTime)
        interval: 15m            #check again within 15 minutes (interval)
        maxEjectionPercent: 100  #All of pods can be ejected (maxEjectionPercent)
